name: qedge6g
channels:
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib>=3.8
  - networkx>=3.2
  - numpy>=1.26
  - pandas>=2.2
  - pyyaml>=6.0
  - scikit-learn>=1.5
  - scipy>=1.13
  - seaborn>=0.13
  - pytest>=8.0
